name: Deploy dev branch

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.DATA_TRIGGER_SECRET}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/BeethovensWerkstatt/api/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "dev"}'
